meta_product_name: "Christmas Gift 2020"
meta_title: "Christmas Gift 2020"
meta_description: "A Christmas gift for the world in the dark COVID times of 2020. This is a non-profit projects of two European friends seperated by many borders, connected through the internet."
meta_image: "cover.png" # should exist in `app/assets/images/`
